import NavigationMenu, { NavMenuItem } from "./NavigationMenu";

const adminMenuItems: NavMenuItem[] = [
    {
        key: "home-admin",
        label: "Inicio",
        path: "/",
        background: "/images/bg-home.jpg",
    },
    {
        key: "home-user",
        label: "Home (Usuario)",
        path: "/",
        background: "/images/bg-home.jpg",
        viewAsUser: true,
    },

    {
        key: "agora-admin",
        label: "Ágora (Admin)",
        path: "/agora",
        background: "/images/bg-agora.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "agora-user",
        label: "Ágora (Usuario)",
        path: "/agora",
        background: "/images/bg-agora-user.jpg",
        viewAsUser: true,
    },
    {
        key: "aboutme-admin",
        label: "Sobre Mi (Admin)",
        path: "/aboutMe",
        background: "/images/bg-aboutme.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "aboutme-user",
        label: "Sobre Mi (Usuario)",
        path: "/aboutMe",
        background: "/images/bg-aboutme-user.jpg",
        viewAsUser: true,
    },
    {
        key: "servicios-admin",
        label: "Servicios (Admin)",
        path: "/services",
        background: "/images/bg-services.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "servicios-user",
        label: "Servicios (Usuario)",
        path: "/services",
        background: "/images/bg-services-user.jpg",
        viewAsUser: true,
    },
    {
        key: "neurodiversidad-admin",
        label: "Neurodiversidad (Admin)",
        path: "/neurodiversity",
        background: "/images/bg-neuro.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "neurodiversidad-user",
        label: "Neurodiversidad (Usuario)",
        path: "/neurodiversity",
        background: "/images/bg-neuro-user.jpg",
        viewAsUser: true,
    },

    {
        key: "cea-admin",
        label: "CEA/TEA (Admin)",
        path: "/cea",
        background: "/images/bg-tea.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "cea-user",
        label: "CEA/TEA (Usuario)",
        path: "/cea",
        background: "/images/bg-tea-user.jpg",
        viewAsUser: true,
    },
    {
        key: "tda-admin",
        label: "TDA/TDH (Admin)",
        path: "/tda_Tdh",
        background: "/images/bg-tdath.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "tda-user",
        label: "TDA/TDH (Usuario)",
        path: "/tda_Tdh",
        background: "/images/bg-tdath-user.jpg",
        viewAsUser: true,
    },
    {
        key: "dificultades-admin",
        label: "Dificultades Aprendizaje (Admin)",
        path: "/learningDifficulties",
        background: "/images/bg-learning.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "dificultades-user",
        label: "Dificultades Aprendizaje (Usuario)",
        path: "/learningDifficulties",
        background: "/images/bg-learning-user.jpg",
        viewAsUser: true,
    },
    {
        key: "condiciones-admin",
        label: "Condiciones Desarrollo (Admin)",
        path: "/developmentConditions",
        background: "/images/bg-development.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "condiciones-user",
        label: "Condiciones Desarrollo (Usuario)",
        path: "/developmentConditions",
        background: "/images/bg-development-user.jpg",
        viewAsUser: true,
    },
    {
        key: "eventos-admin",
        label: "Eventos (Admin)",
        path: "/admin/events",
        background: "/images/bg-events.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "eventos-user",
        label: "Eventos (Usuario)",
        path: "/events",
        background: "/images/bg-events-user.jpg",
        viewAsUser: true,
    },
    {
        key: "blog-admin",
        label: "Blog (Admin)",
        path: "/admin/posts",
        background: "/images/bg-blog.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "blog-user",
        label: "Blog (Usuario)",
        path: "/blog",
        background: "/images/bg-blog-user.jpg",
        viewAsUser: true,
    },
    {
        key: "perfil-admin",
        label: "Perfil",
        path: "/profile",
        background: "/images/bg-profile.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "perfil-user",
        label: "Perfil (Usuario)",
        path: "/profile",
        background: "/images/bg-profile-user.jpg",
        viewAsUser: true,
    },
    {
        key: "usuarios-admin",
        label: "Listado de Usuarios",
        path: "/admin/users",
        background: "/images/bg-users.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "login",
        label: "Login",
        path: "/login",
        background: "/images/bg-login.jpg",
        viewAsUser: true,
    },

    {
        key: "terminos-admin",
        label: "Términos (Admin)",
        path: "/admin/legal/terms",
        background: "/images/bg-legal.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "terminos-user",
        label: "Términos (Usuario)",
        path: "/legal/terms",
        background: "/images/bg-legal-user.jpg",
        viewAsUser: true,
    },
    {
        key: "privacidad-admin",
        label: "Privacidad (Admin)",
        path: "/admin/legal/privacy",
        background: "/images/bg-legal.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "privacidad-user",
        label: "Privacidad (Usuario)",
        path: "/legal/privacy",
        background: "/images/bg-legal-user.jpg",
        viewAsUser: true,
    },
    {
        key: "cookies-admin",
        label: "Cookies (Admin)",
        path: "/admin/legal/cookies",
        background: "/images/bg-legal.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "cookies-user",
        label: "Cookies (Usuario)",
        path: "/legal/cookies",
        background: "/images/bg-legal-user.jpg",
        viewAsUser: true,
    },
    {
        key: "reglas-blog-admin",
        label: "Reglas Blog (Admin)",
        path: "/admin/legal/blog-rules",
        background: "/images/bg-blog.jpg",
        role: "ROLE_ADMIN",
        viewAsUser: false,
    },
    {
        key: "reglas-blog-preview",
        label: "Reglas Blog (Vista Usuario)",
        path: "/legal/blog-rules",
        background: "/images/bg-blog-user.jpg",
        viewAsUser: true,
    },

];

const AdminDashboardMenu = () => <NavigationMenu items={adminMenuItems} />;

export default AdminDashboardMenu;
